### ISSUE TITLE
Move this repository to the 'pybind' organization?

### ISSUE THREAD

**Issue by wjakob** [pybind/cmake_example#1]
Hi Dean,

would you be open to moving this repository to the 'pybind11' organization? (similar to the 'pbtest' pip example which is already there). If so, please go ahead and initiate a transfer, and I'll also add you to the organization.

Thanks,
Wenzel

**Comment by dean0x7d** [comment]
Sure! I tried to initiate the transfer now, but it returned the error: "You don’t have admin rights to pybind".
I've never used the transfer feature on Github before, so maybe I'm doing something wrong.

**Comment by dean0x7d** [comment]
OK, transfer complete. I guess the repo should also be renamed to just `cmake_example` or maybe something simpler?

**Comment by wjakob** [comment]
done, thanks!
