### ISSUE TITLE
How could I let main.cpp include functions written in other source files

### ISSUE THREAD

**Issue by CoinCheung** [pybind/cmake_example#15]
I tried to understand how this example works, but I do not know what lines shall I add to the CMakeLists.txt if my main.cpp have include other headers and called the functions defined in these headers. 

For example, I have a fun.cpp/fun.h sources files: 
```
// fun.h
void print();
// fun.cpp
#include<iostream>
void print() {std::cout << "hello world" << endl;}
```
And in my main.cpp
```
#include<pybind11/pybind11.h>
#include"fun.h"

namespace py = pybind11;

PYBIND11_MODULE(main, m) {
    m.doc() = "some description of this module";

    m.def("print_", &print, "print hello world");
}
```
I tried to write a CMakeLists.txt
```
cmake_minimum_required(VERSION 2.8.12)
project(example)

add_library(fun fun.cpp)

add_subdirectory(pybind11)
pybind11_add_module(main SHARED main.cpp)
```
But this does not work, when I import from python side. What is the correct CMakeList.txt should be  like please ?

**Comment by bstaletic** [comment]
Try this:

```
cmake_minimum_required(VERSION 2.8.12)
project(example)
add_subdirectory(pybind11)
pybind11_add_module(main SHARED main.cpp fun.cpp)
```

According to [the docs](https://pybind11.readthedocs.io/en/stable/compiling.html?highlight=pybind11_add_module#pybind11-add-module), `pybind11_add_module` takes a list of sources.

**Comment by CoinCheung** [comment]
Thank you very much, here I am still puzzled how I could let the module be linked to some so files that is not in the system environment paths. For example, my project has this structure: 
```
|-main.cpp
|-subdirectory-|-fun1.cpp
               |-fun1.h
               |-fun2.cpp
               |-fun2.h
|-libplay.so
|-libplay.h
|-CMakeLists.txt
```
My CMakeLists.txt is like this: 
```
cmake_minimum_required(VERSION 2.8.12)
project(example)

include_directories(./)
link_directories(./)

add_subdirectory(pybind11)
pybind11_add_module(main SHARED main.cpp fun.cpp)

```
But this still does not work, how could I fix it please ?

**Comment by CoinCheung** [comment]
I have no idea how I could add this line to make it work, with ```target_link_libraries```, my CMakeList.txt is like this: 
```
cmake_minimum_required(VERSION 2.8.12)
project(example)

add_library(play SHARED play.cpp)
include_directories(./)
link_directories(./)

add_subdirectory(pybind11)
pybind11_add_module(main SHARED main.cpp fun.cpp)
target_link_libraries(main play)
```
This does not work for me, what is the correct way to use it please ?

**Comment by bstaletic** [comment]
> This does not work for me

You need to give more information than that. How exactly did it not work? How did you run cmake? What exactly did cmake pass to the compiler?

**Comment by CoinCheung** [comment]
Sorry, I should have made it clearer. Provided I have a code like this: 
```
// play.h
void print();
//play.cpp
#include<iostream>
void print() {std::cout << "hello world" << std::endl;}
```
And I compile them into a shared library: 
```
g++ -fPIC play.cpp -shared -o libplay.so
```
Then I use this lib in a main.cpp
```
#include<pybind11/pybind11.h>
#include"play.h"

PYBIND11_MODULE(main, m) {
    m.doc() = "";
    m.def("print", &print, "");
}
```
My CMakeLists.txt is like this:
```
cmake_minimum_required(VERSION 2.8.12)
project(example)

include_directories(./)
link_directories(./)

add_subdirectory(pybind11)
pybind11_add_module(main SHARED main.cpp)
target_link_libraries(main play)
```
but it seems not to work at all. 
I run cmake in the root folder like this: 
```
cmake .
```
And the error message is:
```
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3.7 (found version "3.7") 
-- Found PythonLibs: /usr/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMake Error at CMakeLists.txt:10 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "main".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * pybind11/tools/pybind11Tools.cmake:107 (target_link_libraries)
```
by the way, I am working on archlinux with python3.7 and cmake3.11.4. 
What is the solution to my problem please?

**Comment by bstaletic** [comment]
Did you try doing what the error says and keyworded the call to `target_link_libraries`?
https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html

Use something. `PRIVATE`, `PUBLIC`, whatever works.

**Comment by nuistzhou** [comment]
An additional question, what if I need to bind a method from a header file says `fun1.h`, what shall I write in the `binder.cpp`?

**Comment by bermeom** [comment]
@CoinCheung, I solved it using _include_directories_ in this way, 
`include_directories(SYSTEM  ${PROJECT_SOURCE_DIR}/src/your_folder)`

**Comment by SmaranTum** [comment]
cx

**Comment by henryiii** [comment]
The correct way to do this is to use `target_include_directories(<target_name> PRIVATE <directory>)` (or PUBLIC), see https://cliutils.gitlab.io/modern-cmake/.

**Comment by qgbcs** [comment]
How to target_link_libraries(cashflow OpenSSL::SSL OpenSSL::Crypto)
