### ISSUE TITLE
Cannot install this example from pypi test

### ISSUE THREAD

**Issue by K20shores** [pybind/cmake_example#182]
I'm trying to publish my pybind11 stuff to pypi. I figured I would test out the output for this project. When I run the instructions from [pypi test for this project](https://test.pypi.org/project/cmake-example/), I get an error telling me that no distribution is found 

```
:: pip install -i https://test.pypi.org/simple/ cmake-example                                          
Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement cmake-example (from versions: none)
ERROR: No matching distribution found for cmake-example
```

**Comment by henryiii** [comment]
We don't actually take the "cmake-example" name on TestPyPI. We might have pushed there before but even if we did, Test PyPI can be wiped and cleaned at any time, it's not a long term package index.

PS: I'd highly recommend looking a the scikit_build_example instead; wrapping setuptools is fragile.

**Comment by henryiii** [comment]
https://github.com/pybind/scikit_build_example, yes

**Comment by henryiii** [comment]
Also the guide here: https://learn.scientific-python.org/development/guides/ is helpful.
