### ISSUE TITLE
how to set path of extension

### ISSUE THREAD

**Issue by caishanli** [pybind/cmake_example#33]
Hi:
    I want to set extension's path not to site-packages root, like:
```
site-packages
    cmake_example
        __init__.py
        cmake_example.cp38-win_amd64.pyd
```
   what should I do in setup.py?
Thanks!

**Comment by henryiii** [comment]
Isn't that basically what we have now? What is the current output, if not that?

**Comment by caishanli** [comment]
> Isn't that basically what we have now? What is the current output, if not that?

What we have now is that the pyd file will install to the root of site-packages.
In cmake_example, only one file cmake_example.cp38-win_amd64.pyd need to be installed.
But in most case, we have some other py files too, like matplotlib, in site-packages:
```
matplotlib
    afm.py
    animation.py
    ...
    ft2font.cp38-win_amd64.pyd
    _contour.cp38-win_amd64.pyd
    ...
```

**Comment by caishanli** [comment]
I find that scikit_build_example is the correct one.
So can this repo do the same ?
Thank you

**Comment by caishanli** [comment]
I find that, just add the lib name to extdir in class CMakeBuild.
Thanks!
