### ISSUE TITLE
Where is the ./cmake_example

### ISSUE THREAD

**Issue by wwtx9** [pybind/cmake_example#34]
When I git clone the cmake_example, I do not find ./cmake_example file. And I mkdir build and cmake .. & make, still did not find ./cmake_example. In addition, I run python setup.py install, it still not work. any help?

**Comment by henryiii** [comment]
This makes a Python extension module. So it will be named "cmake_example.<stuff>`, where the `<stuff>` depends on your OS and Python version. For me:

```bash
cmake -S . -B build
cmake --build build
```

produces `./build/cmake_example.cpython-39-darwin.so`.

If you install this with `pip install .`, it will go into your site-packages folder. If you use `-e .` instead, then it will go into a local folder and get simlinked in (more or less) to your site-packages. I recommend following the instructions in the README.

**Comment by wwtx9** [comment]
I see, so when I cmake it, it produces cmake_example.cpython-36m-x86_64-linux-gnu.so. But how python knows this .so. Because when import cmake_example as m in test.py, it shows ModuleNotFoundError: No module named 'cmake_example'

**Comment by henryiii** [comment]
Are you running Python 3.6 on Linux? If so, Python imports things named `<name>.cpython-36m-x86_64-linux-gnu.so` in os.path. The local directory is in the path, so if you have to run it locally, you can start Python in the `/build` directory, or you can add the build directory to the `PYTHONPATH` environment variable or to `os.path` from inside Python.

But it's much better to make a virtual environment and then install to it with `pip install .`.

**Comment by wwtx9** [comment]
@henryiii  Thanks for your reply. really appreciate it. Yes, I am running python3.6 on Ubuntu 18.04. If I want to import c++ module in a python file instead of running locally, do I pip install ./cmake_example.cpython-36m-x86_64-linux-gnu.so?

**Comment by henryiii** [comment]
No, use `pip install .` from the main directory of the example. Pip will install the package defined by setup.py, and you'll then be able to import it in Python anywhere.

If you really want to run it locally, then your python file must be in the same place as your `*.so` file, or you have to manually add it to your path.

**Comment by wwtx9** [comment]
Got it. Thank you very much. One more question. Did pip install . same to python setup.py install?

**Comment by henryiii** [comment]
It's very similar, internally it runs almost the same thing but better (the exact calls depend on if you have a `pyproject.toml` file, and if not, they depend on if `wheel` in installed). In just the right situation, it literally calls `python setup.py install` (but with the setuptools copy of distutils replacing the buggy/old system one).

**Comment by wwtx9** [comment]
Thank you. Really appreciate it.
