### ISSUE TITLE
'build/lib.* does not exist

### ISSUE THREAD

**Issue by tdegeus** [pybind/cmake_example#40]
With my code that is almost identical to this example, I am getting on Linux/macOS (but not on Windows) that 

```
...
 -- Build files have been written to: /tmp/pip-req-build-aua6es75/build/temp.linux-x86_64-3.9
ninja: no work to do.
 running install_lib
 warning: install_lib: 'build/lib.linux-x86_64-3.9' does not exist -- no Python modules to install
```

I.e. the `*.so` is created ok, but in the `build/temp.*` directory. It is never copied to the `build/lib.*` directory. 

For reference, I am trying here : https://github.com/tdegeus/prrng/pull/4

**Comment by tdegeus** [comment]
I was missing a comma in the `setup.py`...

**Comment by aalibasic** [comment]
@tdegeus - can you post the setup.py you were using. I am having the same issue.

**Comment by henryiii** [comment]
https://github.com/tdegeus/prrng/pull/4/commits/f4f1164c335d440a2e0fc05adfb0a91b712da292 I believe.
