### ISSUE TITLE
CMAKE_ARGS for building for conda-forge

### ISSUE THREAD

**Issue by tdegeus** [pybind/cmake_example#52]
I noticed an addition for cross-compilation on macOS here https://github.com/pybind/cmake_example/commit/ce0ea77878522a85da0be13cf9e425626d05827e by @henryiii . In trying to make my feedstock work (https://github.com/conda-forge/gmattensor-feedstock/pull/13) I also got across the suggestion to pass the environment variable `CMAKE_ARGS` [here](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#cross-compiling-builds-for-osx-arm64). Does anyone know if that is really needed? And if so, it might not be so bad to add it to the example.

**Comment by henryiii** [comment]
For conda, that looks like a good idea - it seems they updated them. Not sure if this generally applicable, or just a conda-forge thing, but adding `${CMAKE_ARGS` won't hurt if it's empty.

**Comment by henryiii** [comment]
Though, admittedly, since we run CMake internally, it has to be a change for everyone. Hmm, might discuss it in Scikit-Build first, and also see what they are adding to that variable.
