### ISSUE TITLE
Creating a source distribution (sdist)

### ISSUE THREAD

**Issue by patrikhuber** [pybind/cmake_example#6]
Hi!

The setup.py script here is awesome and works great. I can successfully do `pip install .\myproject` to install locally and `cd myproject && python setup.py bdist_wheel` to create a wheel to distribute for the current platform. However what doesn't really work is creating a source distribution (`sdist`) so others can build it from pypi when a wheel is not available (or on Linux). `python setup.py sdist` runs and creates a .tar.gz, but it doesn't contain any source or CMake files so obviously it can't build. I read that there's different ways of including files in an `sdist` but I can't really figure out how to go on in the case of a CMake project like this. Has any of you worked with that before and encountered this issue?

Thanks!

**Comment by dean0x7d** [comment]
`sdist` should work already. This repository is [tested that way](https://github.com/pybind/cmake_example/blob/a1d26607e07e840a9a8ffbb29363775fcf88d97d/.travis.yml#L56). The non-python files which are included in the distribution need to be specified in the [`MANIFEST.in` file](https://github.com/pybind/cmake_example/blob/master/MANIFEST.in). Maybe this file is missing in your case or doesn't list all the required files?

**Comment by patrikhuber** [comment]
Aah. Completely my bad, apologies. I was actually looking for a file like that in this repo but must have overlooked it. Thanks, working great now!
