### ISSUE TITLE
Kitware cmake wheel

### ISSUE THREAD

**Issue by SylvainCorlay** [pybind/cmake_example#7]
It seems that kitware maintains a wheel for cmake!

https://pypi.python.org/pypi/cmake/

This could be interesting

 - to produce the `pybind11Config.cmake` files even on pypi
 - or projects like this one.

In the case of pybind11, the `CMAKE_INSTALL_PREFIX` would be a parent directory to `locations.distutils_scheme('pybind11', *args, **kwargs)['headers'])` I guess...

**Comment by bhack** [comment]
Any news here?

**Comment by ax3l** [comment]
Works for me in #16, used it in my `requirements.txt` in the linked project.
